### ISSUE TITLE
Blacklist Page

### ISSUE THREAD

**Issue by Enorion** [php-earth/conduct#20]
As discussed in Slack because of the recent Blacklisting of webcodes and webcoder, I thought it might be good to have a public Blacklist for the users to see which websites not to share.

Proposed URL: php.earth/blacklist

It should be linked in the Code of Conduct and kept updated when a new Blacklisting happens.

**Comment by petk** [comment]
I'm not sure that would be something very useful. Besides, having black lists is something we should avoid. Why not doing the opposite and promote websites that are good?

**Comment by petk** [comment]
After thorough research and few internal admin discussions, this won't happen in the near future. Closing. :)
